---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - node_exporter

- name: config line node_exporter_flags
  lineinfile:
    state: present
    line: "{{file_line_node_exporter_flags}}"
    regexp: "^{{file_regexp_node_exporter_flags}}=.*"
    dest: "{{file_dest_node_exporter_flags}}"
    create: True
  tags:
    - node_exporter

- name: remove file node_exporter.cfg
  file:
    state: absent
    path: "{{file_dst_node_exporter_cfg}}"
  notify: reload monit
  tags:
    - node_exporter

- name: create file node_exporter.pf
  template:
    src: "{{file_src_node_exporter_pf}}"
    dest: "{{file_dst_node_exporter_pf}}"
    mode: "{{file_mode_node_exporter_pf}}"
    owner: "{{file_owner_node_exporter_pf}}"
    group: "{{file_group_node_exporter_pf}}"
  notify: reload pf
  when: (node_exporter_pf_state == True)
  tags:
    - node_exporter

- name: remove file node_exporter.pf
  file:
    state: absent
    path: "{{file_dst_node_exporter_pf}}"
  notify: reload pf
  when: (node_exporter_pf_state == False)
  tags:
    - node_exporter

- name: config file includes.conf
  lineinfile:
    state: "{{'present' if (node_exporter_pf_state == True) else 'absent'}}"
    line: "{{file_line_includes_conf}}"
    regexp: "{{file_regexp_includes_conf}}"
    dest: "{{file_dst_includes_conf}}"
    create: True
  notify:
    - validate pf
    - reload pf
  tags:
    - node_exporter

- name: status node_exporter
  command: "{{command_cmd_status_node_exporter}}"
  register: register_status_node_exporter
  changed_when: (register_status_node_exporter.rc > 1)
  failed_when: (register_status_node_exporter.rc > 1)
  check_mode: False
  tags:
    - node_exporter

- name: disable node_exporter
  command: "{{command_cmd_disable_node_exporter}}"
  check_mode: False
  when: register_status_node_exporter.rc == 0
  tags:
    - node_exporter

- name: check node_exporter
  command: "{{command_cmd_check_node_exporter}}"
  register: register_check_node_exporter
  changed_when: (register_check_node_exporter.rc > 1)
  failed_when: (register_check_node_exporter.rc > 1)
  check_mode: False
  tags:
    - node_exporter

- name: stop node_exporter
  command: "{{command_cmd_stop_node_exporter}}"
  check_mode: False
  when: register_check_node_exporter.rc == 0
  tags:
    - node_exporter
