---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - gnu_patch

- name: remove package gnu-patch
  package:
    state: 'absent'
    name: "{{package_name_gnu_patch}}"
  tags:
    - gnu_patch
