---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - wireguard

- name: install package wireguard-tools
  package:
    state: present
    name: "{{package_name_wireguard_tools}}"
  tags:
    - wireguard

- name: create file wireguard.dir
  file:
    state: directory
    path: "{{file_dst_wireguard_dir}}"
    mode: "{{file_mode_wireguard_dir}}"
    owner: "{{file_owner_wireguard_dir}}"
    group: "{{file_group_wireguard_dir}}"
  tags:
    - wireguard

- name: stat file monit.d
  stat:
    path: "{{file_dst_monit_d}}"
  register: register_monit_d
  when: (wireguard_monitor_monit_state == True)
  tags:
    - wireguard

- name: create file monit.d
  file:
    state: directory
    path: "{{file_dst_monit_d}}"
    mode: "{{file_mode_monit_d}}"
    owner: "{{file_owner_monit_d}}"
    group: "{{file_group_monit_d}}"
  when: (wireguard_monitor_monit_state == True) and (register_monit_d.stat.exists == False)
  tags:
    - wireguard

- name: stat file pf.d
  stat:
    path: "{{file_dst_pf_d}}"
  register: register_pf_d
  when: (wireguard_pf_state == True)
  tags:
    - wireguard

- name: create file pf.d
  file:
    state: directory
    path: "{{file_dst_pf_d}}"
    mode: "{{file_mode_pf_d}}"
    owner: "{{file_owner_pf_d}}"
    group: "{{file_group_pf_d}}"
  when: (wireguard_pf_state == True) and (register_pf_d.stat.exists == False)
  tags:
    - wireguard
