---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - periodic

- name: line enable daily output
  replace:
    path: "{{file_dst_daily}}"
    regexp: "{{file_regexp_enable_daily_output}}"
    replace: "{{file_replace_enable_daily_output}}"
  when: (periodic_daily_state == True)
  tags:
    - periodic

- name: line enable daily insecurity output
  replace:
    path: "{{file_dst_daily}}"
    regexp: "{{file_regexp_enable_daily_insecurity_output}}"
    replace: "{{file_replace_enable_daily_insecurity_output}}"
  when: (periodic_daily_state == True)
  tags:
    - periodic

- name: line enable monthly output
  replace:
    path: "{{file_dst_monthly}}"
    regexp: "{{file_regexp_enable_monthly_output}}"
    replace: "{{file_replace_enable_monthly_output}}"
  when: (periodic_monthly_state == True)
  tags:
    - periodic

- name: line enable weekly output
  replace:
    path: "{{file_dst_weekly}}"
    regexp: "{{file_regexp_enable_weekly_output}}"
    replace: "{{file_replace_enable_weekly_output}}"
  when: (periodic_weekly_state == True)
  tags:
    - periodic

- name: line disable daily output
  replace:
    path: "{{file_dst_daily}}"
    regexp: "{{file_regexp_disable_daily_output}}"
    replace: "{{file_replace_disable_daily_output}}"
  when: (periodic_daily_state == False)
  tags:
    - periodic

- name: line disable daily insecurity output
  replace:
    path: "{{file_dst_daily}}"
    regexp: "{{file_regexp_disable_daily_insecurity_output}}"
    replace: "{{file_replace_disable_daily_insecurity_output}}"
  when: (periodic_daily_state == False)
  tags:
    - periodic

- name: line disable monthly output
  replace:
    path: "{{file_dst_monthly}}"
    regexp: "{{file_regexp_disable_monthly_output}}"
    replace: "{{file_replace_disable_monthly_output}}"
  when: (periodic_monthly_state == False)
  tags:
    - periodic

- name: line disable weekly output
  replace:
    path: "{{file_dst_weekly}}"
    regexp: "{{file_regexp_disable_weekly_output}}"
    replace: "{{file_replace_disable_weekly_output}}"
  when: (periodic_weekly_state == False)
  tags:
    - periodic
