---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - nginx

- name: create file nginx.conf
  template:
    src: "{{file_src_nginx_conf}}"
    dest: "{{file_dst_nginx_conf}}"
    mode: "{{file_mode_nginx_conf}}"
    owner: "{{file_owner_nginx_conf}}"
    group: "{{file_group_nginx_conf}}"
  notify:
    - check nginx
    - reload service nginx
  tags:
    - nginx

- name: create file nginx.cfg
  template:
    src: "{{file_src_nginx_cfg}}"
    dest: "{{file_dst_nginx_cfg}}"
    mode: "{{file_mode_nginx_cfg}}"
    owner: "{{file_owner_nginx_cfg}}"
    group: "{{file_group_nginx_cfg}}"
  notify: reload service monit
  when: (nginx_monitor_monit_state == True)
  tags:
    - nginx

- name: remove file nginx.cfg
  file:
    state: absent
    path: "{{file_dst_nginx_cfg}}"
  notify: reload service monit
  when: (nginx_monitor_monit_state == False)
  tags:
    - nginx

- name: create file nginx.pf
  template:
    src: "{{file_src_nginx_pf}}"
    dest: "{{file_dst_nginx_pf}}"
    mode: "{{file_mode_nginx_pf}}"
    owner: "{{file_owner_nginx_pf}}"
    group: "{{file_group_nginx_pf}}"
  notify: reload pf
  when: (nginx_pf_state == True)
  tags:
    - nginx

- name: remove file nginx.pf
  file:
    state: absent
    path: "{{file_dst_nginx_pf}}"
  notify: reload pf
  when: (nginx_pf_state == False)
  tags:
    - nginx

- name: config file includes.conf
  lineinfile:
    state: "{{'present' if (nginx_pf_state == True) else 'absent'}}"
    line: "{{file_line_includes_conf}}"
    regexp: "{{file_regexp_includes_conf}}"
    dest: "{{file_dst_includes_conf}}"
    create: True
  notify:
    - validate pf
    - reload pf
  tags:
    - nginx

- name: status nginx
  command: "{{command_cmd_status_nginx}}"
  register: register_status_nginx
  changed_when: (register_status_nginx.rc > 1)
  failed_when: (register_status_nginx.rc > 1)
  check_mode: False
  tags:
    - nginx

- name: enable nginx
  command: "{{command_cmd_enable_nginx}}"
  check_mode: False
  when: (register_status_nginx.rc == 1)
  tags:
    - nginx

- name: check nginx
  command: "{{command_cmd_check_nginx}}"
  register: register_check_nginx
  changed_when: (register_check_nginx.rc > 1)
  failed_when: (register_check_nginx.rc > 1)
  check_mode: False
  tags:
    - nginx

- name: start nginx
  command: "{{command_cmd_start_nginx}}"
  check_mode: False
  when: (register_check_nginx.rc == 1)
  tags:
    - nginx
