---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - nginx

- name: info nginx
  shell: "{{command_cmd_info_nginx}}"
  register: register_info_nginx
  failed_when: (register_info_nginx.rc > 1)
  check_mode: False
  tags:
    - nginx

- name: disable nginx
  command: "{{command_cmd_disable_nginx}}"
  check_mode: False
  when: register_info_nginx.rc == 0
  tags:
    - nginx

- name: stop nginx
  command: "{{command_cmd_stop_nginx}}"
  check_mode: False
  when: register_info_nginx.rc == 0
  tags:
    - nginx

- name: remove package nginx
  package:
    state: absent
    name: "{{package_name_nginx}}"
  tags:
    - nginx

- name: remove file nginx.conf
  file:
    state: absent
    path: "{{file_dst_nginx_conf}}"
  tags:
    - nginx

- name: remove file dhparam.pem
  file:
    state: absent
    path: "{{file_dst_dhparam_pem}}"
  tags:
    - nginx

- name: remove file vhosts.d
  file:
    state: absent
    path: "{{file_dst_vhosts_d}}"
  tags:
    - nginx

- name: remove file nginx.cfg
  file:
    state: absent
    path: "{{file_dst_nginx_cfg}}"
  notify: reload monit
  tags:
    - nginx

- name: config file includes.conf
  lineinfile:
    state: absent
    regexp: "{{file_regexp_includes_conf}}"
    dest: "{{file_dst_includes_conf}}"
    create: True
  notify:
    - validate pf
    - reload pf
  tags:
    - nginx

- name: remove file nginx.pf
  file:
    state: absent
    path: "{{file_dst_nginx_pf}}"
  notify: reload pf
  tags:
    - nginx
