---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - openntpd

- name: status openntpd
  command: "{{command_cmd_status_openntpd}}"
  register: register_status_openntpd
  changed_when: (register_status_openntpd.rc > 1)
  failed_when: (register_status_openntpd.rc > 1)
  check_mode: 'no'
  tags:
    - openntpd

- name: disable openntpd
  command: "{{command_cmd_disable_openntpd}}"
  check_mode: 'no'
  when: register_status_openntpd.rc == 0
  tags:
    - openntpd

- name: check openntpd
  command: "{{command_cmd_check_openntpd}}"
  register: register_check_openntpd
  changed_when: (register_check_openntpd.rc > 1)
  failed_when: (register_check_openntpd.rc > 1)
  check_mode: 'no'
  tags:
    - openntpd

- name: stop openntpd
  command: "{{command_cmd_stop_openntpd}}"
  check_mode: 'no'
  when: register_check_openntpd.rc == 0
  tags:
    - openntpd

- name: remove file openntpd.cfg
  file:
    state: 'absent'
    path: "{{file_dst_openntpd_cfg}}"
  notify: reload service monit
  tags:
    - openntpd

- name: remove cron openntpd_check-time
  cron:
    state: 'absent'
    name: "{{cron_name_openntpd_check_time}}"
    user: "{{cron_user_openntpd_check_time}}"
  tags:
    - openntpd

- name: remove file openntpd_check-time
  file:
    state: 'absent'
    path: "{{file_dst_openntpd_check_time}}"
  tags:
    - openntpd
