---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - unbound

- name: status unbound
  command: "{{command_cmd_status_unbound}}"
  register: register_status_unbound
  changed_when: (register_status_unbound.rc > 1)
  failed_when: (register_status_unbound.rc > 1)
  check_mode: False
  tags:
    - unbound

- name: disable unbound
  command: "{{command_cmd_disable_unbound}}"
  check_mode: False
  when: register_status_unbound.rc == 0
  tags:
    - unbound

- name: check unbound
  command: "{{command_cmd_check_unbound}}"
  register: register_check_unbound
  changed_when: (register_check_unbound.rc > 1)
  failed_when: (register_check_unbound.rc > 1)
  check_mode: False
  tags:
    - unbound

- name: stop unbound
  command: "{{command_cmd_stop_unbound}}"
  check_mode: False
  when: register_check_unbound.rc == 0
  tags:
    - unbound

- name: remove file unbound.cfg
  file:
    state: absent
    path: "{{file_dst_unbound_cfg}}"
  notify: reload monit
  tags:
    - unbound

- name: config file includes.conf
  lineinfile:
    state: absent
    regexp: "{{file_regexp_includes_conf}}"
    dest: "{{file_dst_includes_conf}}"
    create: True
  notify:
    - validate pf
    - reload pf
  tags:
    - unbound

- name: remove file unbound.pf
  file:
    state: absent
    path: "{{file_dst_unbound_pf}}"
  notify: reload pf
  tags:
    - unbound
