---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - sysctl

- name: remove file sysctl.conf
  file:
    state: 'absent'
    path: "{{file_dst_sysctl_conf}}"
  tags:
    - sysctl
