---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - vim

- name: install package vim
  package:
    state: 'present'
    name: "{{package_name_vim}}"
  tags:
    - vim

- name: create file defaults.vim
  template:
    src: "{{file_src_defaults_vim}}"
    dest: "{{file_dst_defaults_vim}}"
    mode: "{{file_mode_defaults_vim}}"
    owner: "{{file_owner_defaults_vim}}"
    group: "{{file_group_defaults_vim}}"
  tags:
    - vim

- name: remove file vimrc
  file:
    state: 'absent'
    path: "{{file_dst_vimrc}}"
  tags:
    - vim
