---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - socat

- name: remove package socat
  package:
    state: 'absent'
    name: "{{package_name_socat}}"
  tags:
    - socat
