---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - openntpd

- name: create file ntpd.conf
  template:
    src: "{{file_src_ntpd_conf}}"
    dest: "{{file_dst_ntpd_conf}}"
    mode: "{{file_mode_ntpd_conf}}"
    owner: "{{file_owner_ntpd_conf}}"
    group: "{{file_group_ntpd_conf}}"
  tags:
    - openntpd

- name: remove file openntpd_check-time
  file:
    state: absent
    path: "{{file_dst_openntpd_check_time}}"
  tags:
    - openntpd

- name: create cron openntpd_check-time
  cron:
    state: present
    disabled: True
    name: "{{cron_name_openntpd_check_time}}"
    day: "{{cron_day_openntpd_check_time}}"
    hour: "{{cron_hour_openntpd_check_time}}"
    minute: "{{cron_minute_openntpd_check_time}}"
    month: "{{cron_month_openntpd_check_time}}"
    weekday: "{{cron_weekday_openntpd_check_time}}"
    user: "{{cron_user_openntpd_check_time}}"
    job: "{{cron_job_openntpd_check_time}}"
  tags:
    - openntpd

- name: remove file openntpd.cfg
  file:
    state: absent
    path: "{{file_dst_openntpd_cfg}}"
  notify: reload service monit
  tags:
    - openntpd

- name: create file openntpd.pf
  template:
    src: "{{file_src_openntpd_pf}}"
    dest: "{{file_dst_openntpd_pf}}"
    mode: "{{file_mode_openntpd_pf}}"
    owner: "{{file_owner_openntpd_pf}}"
    group: "{{file_group_openntpd_pf}}"
  notify: reload pf
  when: (openntpd_pf_state == True)
  tags:
    - openntpd

- name: remove file openntpd.pf
  file:
    state: absent
    path: "{{file_dst_openntpd_pf}}"
  notify: reload pf
  when: (openntpd_pf_state == False)
  tags:
    - openntpd

- name: config file includes.conf
  lineinfile:
    state: "{{'present' if (openntpd_pf_state == True) else 'absent'}}"
    line: "{{file_line_includes_conf}}"
    regexp: "{{file_regexp_includes_conf}}"
    dest: "{{file_dst_includes_conf}}"
    create: True
  notify:
    - validate pf
    - reload pf
  tags:
    - openntpd

- name: status openntpd
  command: "{{command_cmd_status_openntpd}}"
  register: register_status_openntpd
  changed_when: (register_status_openntpd.rc > 1)
  failed_when: (register_status_openntpd.rc > 1)
  check_mode: False
  tags:
    - openntpd

- name: disable openntpd
  command: "{{command_cmd_disable_openntpd}}"
  check_mode: False
  when: register_status_openntpd.rc == 0
  tags:
    - openntpd

- name: check openntpd
  command: "{{command_cmd_check_openntpd}}"
  register: register_check_openntpd
  changed_when: (register_check_openntpd.rc > 1)
  failed_when: (register_check_openntpd.rc > 1)
  check_mode: False
  tags:
    - openntpd

- name: stop openntpd
  command: "{{command_cmd_stop_openntpd}}"
  check_mode: False
  when: register_check_openntpd.rc == 0
  tags:
    - openntpd
