---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - moreutils

- name: install package moreutils
  package:
    state: 'present'
    name: "{{package_name_moreutils}}"
  tags:
    - moreutils
