---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - opensmtpd

- name: status opensmtpd
  command: "{{command_cmd_status_opensmtpd}}"
  register: register_status_opensmtpd
  changed_when: (register_status_opensmtpd.rc > 1)
  failed_when: (register_status_opensmtpd.rc > 1)
  check_mode: False
  tags:
    - opensmtpd

- name: disable opensmtpd
  command: "{{command_cmd_disable_opensmtpd}}"
  check_mode: False
  when: register_status_opensmtpd.rc == 0
  tags:
    - opensmtpd

- name: check opensmtpd
  command: "{{command_cmd_check_opensmtpd}}"
  register: register_check_opensmtpd
  changed_when: (register_check_opensmtpd.rc > 1)
  failed_when: (register_check_opensmtpd.rc > 1)
  check_mode: False
  tags:
    - opensmtpd

- name: stop opensmtpd
  command: "{{command_cmd_stop_opensmtpd}}"
  check_mode: False
  when: register_check_opensmtpd.rc == 0
  tags:
    - opensmtpd

- name: remove file opensmtpd.cfg
  file:
    state: absent
    path: "{{file_dst_opensmtpd_cfg}}"
  notify: reload service monit
  tags:
    - opensmtpd

- name: remove file secrets
  file:
    state: absent
    path: "{{file_dst_secrets}}"
  tags:
    - opensmtpd
