---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'

- name: validate pf
  shell: "{{command_cmd_validate_pf}}"

- name: reload pf
  shell: "{{command_cmd_reload_pf}}"
