---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - restic

- name: create cron restic_run-backup
  cron:
    state: present
    disabled: True
    name: "{{cron_name_restic_run_backup}}"
    day: "{{cron_day_restic_run_backup}}"
    hour: "{{cron_hour_restic_run_backup}}"
    minute: "{{cron_minute_restic_run_backup}}"
    month: "{{cron_month_restic_run_backup}}"
    weekday: "{{cron_weekday_restic_run_backup}}"
    user: "{{cron_user_restic_run_backup}}"
    job: "{{cron_job_restic_run_backup}}"
  tags:
    - restic

- name: create file restic.pf
  template:
    src: "{{file_src_restic_pf}}"
    dest: "{{file_dst_restic_pf}}"
    mode: "{{file_mode_restic_pf}}"
    owner: "{{file_owner_restic_pf}}"
    group: "{{file_group_restic_pf}}"
  notify: reload pf
  when: (restic_pf_state == True)
  tags:
    - restic

- name: remove file restic.pf
  file:
    state: absent
    path: "{{file_dst_restic_pf}}"
  notify: reload pf
  when: (restic_pf_state == False)
  tags:
    - restic

- name: config file includes.conf
  lineinfile:
    state: "{{'present' if (restic_pf_state == True) else 'absent'}}"
    line: "{{file_line_includes_conf}}"
    regexp: "{{file_regexp_includes_conf}}"
    dest: "{{file_dst_includes_conf}}"
    create: True
  notify:
    - validate pf
    - reload pf
  tags:
    - restic
