---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - restic

- name: install package restic
  package:
    state: present
    name: "{{package_name_restic}}"
  tags:
    - restic

- name: create file restic_etc.dir
  file:
    state: directory
    path: "{{file_dst_restic_etc_dir}}"
    mode: "{{file_mode_restic_etc_dir}}"
    owner: "{{file_owner_restic_etc_dir}}"
    group: "{{file_group_restic_etc_dir}}"
  tags:
    - restic

- name: create file restic_log.dir
  file:
    state: directory
    path: "{{file_dst_restic_log_dir}}"
    mode: "{{file_mode_restic_log_dir}}"
    owner: "{{file_owner_restic_log_dir}}"
    group: "{{file_group_restic_log_dir}}"
  tags:
    - restic

- name: create file exclude.conf
  template:
    src: "{{file_src_exclude_conf}}"
    dest: "{{file_dst_exclude_conf}}"
    mode: "{{file_mode_exclude_conf}}"
    owner: "{{file_owner_exclude_conf}}"
    group: "{{file_group_exclude_conf}}"
  tags:
    - restic

- name: create file include.conf
  template:
    src: "{{file_src_include_conf}}"
    dest: "{{file_dst_include_conf}}"
    mode: "{{file_mode_include_conf}}"
    owner: "{{file_owner_include_conf}}"
    group: "{{file_group_include_conf}}"
  tags:
    - restic

- name: create file password.conf
  template:
    src: "{{file_src_password_conf}}"
    dest: "{{file_dst_password_conf}}"
    mode: "{{file_mode_password_conf}}"
    owner: "{{file_owner_password_conf}}"
    group: "{{file_group_password_conf}}"
  no_log: True
  tags:
    - restic

- name: create file repository.conf
  template:
    src: "{{file_src_repository_conf}}"
    dest: "{{file_dst_repository_conf}}"
    mode: "{{file_mode_repository_conf}}"
    owner: "{{file_owner_repository_conf}}"
    group: "{{file_group_repository_conf}}"
  no_log: True
  tags:
    - restic

- name: create file restic.log
  copy:
    content: ''
    force: False
    dest: "{{file_dst_restic_log}}"
    mode: "{{file_mode_restic_log}}"
    owner: "{{file_owner_restic_log}}"
    group: "{{file_group_restic_log}}"
  tags:
    - restic

- name: create file restic_run-backup
  template:
    src: "{{file_src_restic_run_backup}}"
    dest: "{{file_dst_restic_run_backup}}"
    mode: "{{file_mode_restic_run_backup}}"
    owner: "{{file_owner_restic_run_backup}}"
    group: "{{file_group_restic_run_backup}}"
  no_log: True
  tags:
    - restic

- name: stat file pf.d
  stat:
    path: "{{file_dst_pf_d}}"
  register: register_pf_d
  when: (restic_pf_state == True)
  tags:
    - restic

- name: create file pf.d
  file:
    state: directory
    path: "{{file_dst_pf_d}}"
    mode: "{{file_mode_pf_d}}"
    owner: "{{file_owner_pf_d}}"
    group: "{{file_group_pf_d}}"
  when: (restic_pf_state == True) and (register_pf_d.stat.exists == False)
  tags:
    - restic
