---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - gnu_sed

- name: remove package gnu-sed
  package:
    state: 'absent'
    name: "{{package_name_gnu_sed}}"
  tags:
    - gnu_sed
