---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - opensmtpd

- name: create file aliases
  template:
    src: "{{file_src_aliases}}"
    dest: "{{file_dst_aliases}}"
    mode: "{{file_mode_aliases}}"
    owner: "{{file_owner_aliases}}"
    group: "{{file_group_aliases}}"
  tags:
    - opensmtpd

- name: create file secrets
  template:
    src: "{{file_src_secrets}}"
    dest: "{{file_dst_secrets}}"
    mode: "{{file_mode_secrets}}"
    owner: "{{file_owner_secrets}}"
    group: "{{file_group_secrets}}"
  no_log: True
  tags:
    - opensmtpd

- name: create file smtpd.conf
  template:
    src: "{{file_src_smtpd_conf}}"
    dest: "{{file_dst_smtpd_conf}}"
    mode: "{{file_mode_smtpd_conf}}"
    owner: "{{file_owner_smtpd_conf}}"
    group: "{{file_group_smtpd_conf}}"
  tags:
    - opensmtpd

- name: remove file opensmtpd.cfg
  file:
    state: absent
    path: "{{file_dst_opensmtpd_cfg}}"
  notify: reload monit
  tags:
    - opensmtpd

- name: create file opensmtpd.pf
  template:
    src: "{{file_src_opensmtpd_pf}}"
    dest: "{{file_dst_opensmtpd_pf}}"
    mode: "{{file_mode_opensmtpd_pf}}"
    owner: "{{file_owner_opensmtpd_pf}}"
    group: "{{file_group_opensmtpd_pf}}"
  notify: reload pf
  when: (opensmtpd_pf_state == True)
  tags:
    - opensmtpd

- name: remove file opensmtpd.pf
  file:
    state: absent
    path: "{{file_dst_opensmtpd_pf}}"
  notify: reload pf
  when: (opensmtpd_pf_state == False)
  tags:
    - opensmtpd

- name: config file includes.conf
  lineinfile:
    state: "{{'present' if (opensmtpd_pf_state == True) else 'absent'}}"
    line: "{{file_line_includes_conf}}"
    regexp: "{{file_regexp_includes_conf}}"
    dest: "{{file_dst_includes_conf}}"
    create: True
  notify:
    - validate pf
    - reload pf
  tags:
    - opensmtpd

- name: status opensmtpd
  command: "{{command_cmd_status_opensmtpd}}"
  register: register_status_opensmtpd
  changed_when: (register_status_opensmtpd.rc > 1)
  failed_when: (register_status_opensmtpd.rc > 1)
  check_mode: False
  tags:
    - opensmtpd

- name: disable opensmtpd
  command: "{{command_cmd_disable_opensmtpd}}"
  check_mode: False
  when: register_status_opensmtpd.rc == 0
  tags:
    - opensmtpd

- name: check opensmtpd
  command: "{{command_cmd_check_opensmtpd}}"
  register: register_check_opensmtpd
  changed_when: (register_check_opensmtpd.rc > 1)
  failed_when: (register_check_opensmtpd.rc > 1)
  check_mode: False
  tags:
    - opensmtpd

- name: stop opensmtpd
  command: "{{command_cmd_stop_opensmtpd}}"
  check_mode: False
  when: register_check_opensmtpd.rc == 0
  tags:
    - opensmtpd
