---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - openssh

- name: create file banner
  template:
    src: "{{file_src_banner}}"
    dest: "{{file_dst_banner}}"
    mode: "{{file_mode_banner}}"
    owner: "{{file_owner_banner}}"
    group: "{{file_group_banner}}"
  tags:
    - openssh

- name: create file moduli
  template:
    src: "{{file_src_moduli}}"
    dest: "{{file_dst_moduli}}"
    mode: "{{file_mode_moduli}}"
    owner: "{{file_owner_moduli}}"
    group: "{{file_group_moduli}}"
  tags:
    - openssh

- name: create file ssh_config
  template:
    src: "{{file_src_ssh_config}}"
    dest: "{{file_dst_ssh_config}}"
    mode: "{{file_mode_ssh_config}}"
    owner: "{{file_owner_ssh_config}}"
    group: "{{file_group_ssh_config}}"
  tags:
    - openssh

- name: create file sshd_config
  template:
    src: "{{file_src_sshd_config}}"
    dest: "{{file_dst_sshd_config}}"
    mode: "{{file_mode_sshd_config}}"
    owner: "{{file_owner_sshd_config}}"
    group: "{{file_group_sshd_config}}"
  tags:
    - openssh

- name: remove file openssh.cfg
  file:
    state: absent
    path: "{{file_dst_openssh_cfg}}"
  notify: reload service monit
  tags:
    - openssh

- name: create file openssh.pf
  template:
    src: "{{file_src_openssh_pf}}"
    dest: "{{file_dst_openssh_pf}}"
    mode: "{{file_mode_openssh_pf}}"
    owner: "{{file_owner_openssh_pf}}"
    group: "{{file_group_openssh_pf}}"
  notify: reload pf
  when: (openssh_pf_state == True)
  tags:
    - openssh

- name: remove file openssh.pf
  file:
    state: absent
    path: "{{file_dst_openssh_pf}}"
  notify: reload pf
  when: (openssh_pf_state == False)
  tags:
    - openssh

- name: config file includes.conf
  lineinfile:
    state: "{{'present' if (openssh_pf_state == True) else 'absent'}}"
    line: "{{file_line_includes_conf}}"
    regexp: "{{file_regexp_includes_conf}}"
    dest: "{{file_dst_includes_conf}}"
    create: True
  notify:
    - validate pf
    - reload pf
  tags:
    - openssh

- name: status openssh
  command: "{{command_cmd_status_openssh}}"
  register: register_status_openssh
  changed_when: (register_status_openssh.rc > 1)
  failed_when: (register_status_openssh.rc > 1)
  check_mode: False
  tags:
    - openssh

- name: disable openssh
  command: "{{command_cmd_disable_openssh}}"
  check_mode: False
  when: register_status_openssh.rc == 0
  tags:
    - openssh

- name: check openssh
  command: "{{command_cmd_check_openssh}}"
  register: register_check_openssh
  changed_when: (register_check_openssh.rc > 1)
  failed_when: (register_check_openssh.rc > 1)
  check_mode: False
  tags:
    - openssh

- name: stop openssh
  command: "{{command_cmd_stop_openssh}}"
  check_mode: False
  when: register_check_openssh.rc == 0
  tags:
    - openssh
