---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - motd

- name: line enable motd-patch
  lineinfile:
    state: 'present'
    line: "\t{{file_line_motd_patch}} # Ansible: Enable motd-patch"
    regexp: "{{file_regexp_motd_patch}}"
    dest: "{{file_dst_motd_patch}}"
    create: 'yes'
  tags:
    - motd
