---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - tcpreplay

- name: remove package tcpreplay
  package:
    state: 'absent'
    name: "{{package_name_tcpreplay}}"
  tags:
    - tcpreplay
