---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - rest_server

- name: create file rest_server.service
  template:
    src: "{{file_src_rest_server_service}}"
    dest: "{{file_dst_rest_server_service}}"
    mode: "{{file_mode_rest_server_service}}"
    owner: "{{file_owner_rest_server_service}}"
    group: "{{file_group_rest_server_service}}"
  tags:
    - rest_server

- name: remove file rest_server.cfg
  file:
    state: absent
    path: "{{file_dst_rest_server_cfg}}"
  notify: reload monit
  tags:
    - rest_server

- name: create file rest_server.pf
  template:
    src: "{{file_src_rest_server_pf}}"
    dest: "{{file_dst_rest_server_pf}}"
    mode: "{{file_mode_rest_server_pf}}"
    owner: "{{file_owner_rest_server_pf}}"
    group: "{{file_group_rest_server_pf}}"
  notify: reload pf
  when: (rest_server_pf_state == True)
  tags:
    - rest_server

- name: remove file rest_server.pf
  file:
    state: absent
    path: "{{file_dst_rest_server_pf}}"
  notify: reload pf
  when: (rest_server_pf_state == False)
  tags:
    - rest_server

- name: config file includes.conf
  lineinfile:
    state: "{{'present' if (rest_server_pf_state == True) else 'absent'}}"
    line: "{{file_line_includes_conf}}"
    regexp: "{{file_regexp_includes_conf}}"
    dest: "{{file_dst_includes_conf}}"
    create: True
  notify:
    - validate pf
    - reload pf
  tags:
    - rest_server

- name: status rest_server
  command: "{{command_cmd_status_rest_server}}"
  register: register_status_rest_server
  changed_when: (register_status_rest_server.rc > 1)
  failed_when: (register_status_rest_server.rc > 1)
  check_mode: False
  tags:
    - rest_server

- name: disable rest_server
  command: "{{command_cmd_disable_rest_server}}"
  check_mode: False
  when: register_status_rest_server.rc == 0
  tags:
    - rest_server

- name: check rest_server
  command: "{{command_cmd_check_rest_server}}"
  register: register_check_rest_server
  changed_when: (register_check_rest_server.rc > 1)
  failed_when: (register_check_rest_server.rc > 1)
  check_mode: False
  tags:
    - rest_server

- name: stop rest_server
  command: "{{command_cmd_stop_rest_server}}"
  check_mode: False
  when: register_check_rest_server.rc == 0
  tags:
    - rest_server

- name: stop service rest_server
  service:
    state: stopped
    enabled: False
    name: "{{service_name_rest_server}}"
  tags:
    - rest_server
