---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'

- name: run netstart
  command: "{{command_cmd_run_netstart}}"
