---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - monit

- name: create file monitrc
  template:
    src: "{{file_src_monitrc}}"
    dest: "{{file_dst_monitrc}}"
    mode: "{{file_mode_monitrc}}"
    owner: "{{file_owner_monitrc}}"
    group: "{{file_group_monitrc}}"
  tags:
    - monit

- name: create file monit.pf
  template:
    src: "{{file_src_monit_pf}}"
    dest: "{{file_dst_monit_pf}}"
    mode: "{{file_mode_monit_pf}}"
    owner: "{{file_owner_monit_pf}}"
    group: "{{file_group_monit_pf}}"
  notify: reload pf
  when: (monit_pf_state == True)
  tags:
    - monit

- name: remove file monit.pf
  file:
    state: absent
    path: "{{file_dst_monit_pf}}"
  notify: reload pf
  when: (monit_pf_state == False)
  tags:
    - monit

- name: config file includes.conf
  lineinfile:
    state: "{{'present' if (monit_pf_state == True) else 'absent'}}"
    line: "{{file_line_includes_conf}}"
    regexp: "{{file_regexp_includes_conf}}"
    dest: "{{file_dst_includes_conf}}"
    create: True
  notify:
    - validate pf
    - reload pf
  tags:
    - monit

- name: status monit
  command: "{{command_cmd_status_monit}}"
  register: register_status_monit
  changed_when: (register_status_monit.rc > 1)
  failed_when: (register_status_monit.rc > 1)
  check_mode: False
  tags:
    - monit

- name: disable monit
  command: "{{command_cmd_disable_monit}}"
  check_mode: False
  when: register_status_monit.rc == 0
  tags:
    - monit

- name: check monit
  command: "{{command_cmd_check_monit}}"
  register: register_check_monit
  changed_when: (register_check_monit.rc > 1)
  failed_when: (register_check_monit.rc > 1)
  check_mode: False
  tags:
    - monit

- name: stop monit
  command: "{{command_cmd_stop_monit}}"
  check_mode: False
  when: register_check_monit.rc == 0
  tags:
    - monit
