---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - monit

- name: install package monit
  package:
    state: present
    name: "{{package_name_monit}}"
  tags:
    - monit

- name: create file monit.d
  file:
    state: directory
    path: "{{file_dst_monit_d}}"
    mode: "{{file_mode_monit_d}}"
    owner: "{{file_owner_monit_d}}"
    group: "{{file_group_monit_d}}"
  tags:
    - monit

- name: stat file pf.d
  stat:
    path: "{{file_dst_pf_d}}"
  register: register_pf_d
  when: (monit_pf_state == True)
  tags:
    - monit

- name: create file pf.d
  file:
    state: directory
    path: "{{file_dst_pf_d}}"
    mode: "{{file_mode_pf_d}}"
    owner: "{{file_owner_pf_d}}"
    group: "{{file_group_pf_d}}"
  when: (monit_pf_state == True) and (register_pf_d.stat.exists == False)
  tags:
    - monit
