---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - monit

- name: info monit
  shell: "{{command_cmd_info_monit}}"
  register: register_info_monit
  failed_when: (register_info_monit.rc > 1)
  check_mode: False
  tags:
    - monit

- name: disable monit
  command: "{{command_cmd_disable_monit}}"
  check_mode: False
  when: register_info_monit.rc == 0
  tags:
    - monit

- name: stop monit
  command: "{{command_cmd_stop_monit}}"
  check_mode: False
  when: register_info_monit.rc == 0
  tags:
    - monit

- name: remove package monit
  package:
    state: absent
    name: "{{package_name_monit}}"
  tags:
    - monit

- name: remove file monit.d
  file:
    state: absent
    path: "{{file_dst_monit_d}}"
  tags:
    - monit

- name: remove file monitrc
  file:
    state: absent
    path: "{{file_dst_monitrc}}"
  tags:
    - monit

- name: config file includes.conf
  lineinfile:
    state: absent
    regexp: "{{file_regexp_includes_conf}}"
    dest: "{{file_dst_includes_conf}}"
    create: True
  notify:
    - validate pf
    - reload pf
  tags:
    - monit

- name: remove file monit.pf
  file:
    state: absent
    path: "{{file_dst_monit_pf}}"
  notify: reload pf
  tags:
    - monit
