---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'

- name: restart service ipmi_exporter
  service:
    state: restarted
    name: "{{service_name_ipmi_exporter}}"

- name: validate monit
  shell: "{{command_cmd_validate_monit}}"

- name: reload monit
  shell: "{{command_cmd_reload_monit}}"

- name: validate pf
  shell: "{{command_cmd_validate_pf}}"

- name: reload pf
  shell: "{{command_cmd_reload_pf}}"
