---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - bash

- name: install package bash
  package:
    state: present
    name: "{{package_name_bash}}"
  tags:
    - bash

- name: create file profile.d
  file:
    state: directory
    path: "{{file_dst_profile_d}}"
    mode: "{{file_mode_profile_d}}"
    owner: "{{file_owner_profile_d}}"
    group: "{{file_group_profile_d}}"
  tags:
    - bash

- name: create file bash.bash
  template:
    src: "{{file_src_bash_bash}}"
    dest: "{{file_dst_bash_bash}}"
    mode: "{{file_mode_bash_bash}}"
    owner: "{{file_owner_bash_bash}}"
    group: "{{file_group_bash_bash}}"
  tags:
    - bash

- name: create file zz_bash.bash
  template:
    src: "{{file_src_zz_bash_bash}}"
    dest: "{{file_dst_zz_bash_bash}}"
    mode: "{{file_mode_zz_bash_bash}}"
    owner: "{{file_owner_zz_bash_bash}}"
    group: "{{file_group_zz_bash_bash}}"
  tags:
    - bash
