---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - bash

- name: remove package bash
  package:
    state: absent
    name: "{{package_name_bash}}"
  tags:
    - bash

- name: remove file profile.d
  file:
    state: absent
    path: "{{file_dst_profile_d}}"
  tags:
    - bash
