---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - ca_certificate

- name: remove file certs.dir
  file:
    state: absent
    path: "{{file_dst_certs_dir}}"
  tags:
    - ca_certificate
