---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - pf

- name: create file pf.d
  file:
    state: directory
    path: "{{file_dst_pf_d}}"
    mode: "{{file_mode_pf_d}}"
    owner: "{{file_owner_pf_d}}"
    group: "{{file_group_pf_d}}"
  tags:
    - pf
