---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - pf

- name: status pf
  command: "{{command_cmd_status_pf}}"
  register: register_status_pf
  changed_when: (register_status_pf.rc > 1)
  failed_when: (register_status_pf.rc > 1)
  check_mode: False
  tags:
    - pf

- name: disable pf
  command: "{{command_cmd_disable_pf}}"
  when: (register_status_pf.rc == 0)
  check_mode: False
  tags:
    - pf

- name: check pf
  shell: "{{command_cmd_check_pf}}"
  register: register_check_pf
  changed_when: (register_check_pf.rc > 1)
  failed_when: (register_check_pf.rc > 1)
  check_mode: False
  tags:
    - pf

- name: stop pf
  command: "{{command_cmd_stop_pf}}"
  when: (register_check_pf.rc == 0)
  check_mode: False
  tags:
    - pf

- name: remove file pf.conf
  file:
    state: absent
    path: "{{file_dst_pf_conf}}"
  tags:
    - pf

- name: remove file pf.d
  file:
    state: absent
    path: "{{file_dst_pf_d}}"
  tags:
    - pf
