---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'

- name: validate monit
  command: "{{command_cmd_validate_monit}}"

- name: reload service monit
  service:
    state: reloaded
    name: "{{service_name_monit}}"

- name: restart service monit
  service:
    state: restarted
    name: "{{service_name_monit}}"

- name: validate pf
  shell: "{{command_cmd_validate_pf}}"

- name: reload pf
  shell: "{{command_cmd_reload_pf}}"
