---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - hping3

- name: remove package hping3
  package:
    state: 'absent'
    name: "{{package_name_hping3}}"
  tags:
    - hping3
