---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - tmux

- name: remove file tmux.conf
  file:
    state: absent
    path: "{{file_dst_tmux_conf}}"
  tags:
    - tmux
