---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - wireguard

- name: remove package wireguard-tools
  package:
    state: 'absent'
    name: "{{package_name_wireguard_tools}}"
  tags:
    - wireguard

- name: remove file wireguard.dir
  file:
    state: 'absent'
    path: "{{file_dst_wireguard_dir}}"
  tags:
    - wireguard
