---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - squid

- name: install package squid
  package:
    state: present
    name: "{{package_name_squid}}"
  tags:
    - squid

- name: create file acl.dir
  file:
    state: directory
    path: "{{file_dst_acl_dir}}"
    mode: "{{file_mode_acl_dir}}"
    owner: "{{file_owner_acl_dir}}"
    group: "{{file_group_acl_dir}}"
  tags:
    - squid

- name: stat file monit.d
  stat:
    path: "{{file_dst_monit_d}}"
  register: register_monit_d
  when: (squid_monitor_monit_state == True)
  tags:
    - squid

- name: create file monit.d
  file:
    state: directory
    path: "{{file_dst_monit_d}}"
    mode: "{{file_mode_monit_d}}"
    owner: "{{file_owner_monit_d}}"
    group: "{{file_group_monit_d}}"
  when: (squid_monitor_monit_state == True) and (register_monit_d.stat.exists == False)
  tags:
    - squid

- name: stat file pf.d
  stat:
    path: "{{file_dst_pf_d}}"
  register: register_pf_d
  when: (squid_pf_state == True)
  tags:
    - squid

- name: create file pf.d
  file:
    state: directory
    path: "{{file_dst_pf_d}}"
    mode: "{{file_mode_pf_d}}"
    owner: "{{file_owner_pf_d}}"
    group: "{{file_group_pf_d}}"
  when: (squid_pf_state == True) and (register_pf_d.stat.exists == False)
  tags:
    - squid
