---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - nsd

- name: stat file monit.d
  stat:
    path: "{{file_dst_monit_d}}"
  register: register_monit_d
  when: (nsd_monitor_monit_state == True)
  tags:
    - nsd

- name: create file monit.d
  file:
    state: directory
    path: "{{file_dst_monit_d}}"
    mode: "{{file_mode_monit_d}}"
    owner: "{{file_owner_monit_d}}"
    group: "{{file_group_monit_d}}"
  when: (nsd_monitor_monit_state == True) and (register_monit_d.stat.exists == False)
  tags:
    - nsd

- name: check service monit
  shell: "{{command_cmd_check_service_monit}}"
  register: register_check_service_monit
  changed_when: (register_check_service_monit.rc > 2)
  failed_when: (register_check_service_monit.rc > 2)
  check_mode: False
  tags:
    - nsd

- name: stat file pf.d
  stat:
    path: "{{file_dst_pf_d}}"
  register: register_pf_d
  when: (nsd_pf_state == True)
  tags:
    - nsd

- name: create file pf.d
  file:
    state: directory
    path: "{{file_dst_pf_d}}"
    mode: "{{file_mode_pf_d}}"
    owner: "{{file_owner_pf_d}}"
    group: "{{file_group_pf_d}}"
  when: (nsd_pf_state == True) and (register_pf_d.stat.exists == False)
  tags:
    - nsd

- name: check pf
  shell: "{{command_cmd_check_pf}}"
  register: register_check_pf
  changed_when: (register_check_pf.rc > 2)
  failed_when: (register_check_pf.rc > 2)
  check_mode: False
  tags:
    - nsd
