---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - openbsd_syslogd

- name: remove file syslogd.cfg
  file:
    state: absent
    path: "{{file_dst_syslogd_cfg}}"
  notify: reload service monit
  tags:
    - openbsd_syslogd
