---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - nsd

- name: create file nsd.conf
  template:
    src: "{{file_src_nsd_conf}}"
    dest: "{{file_dst_nsd_conf}}"
    mode: "{{file_mode_nsd_conf}}"
    owner: "{{file_owner_nsd_conf}}"
    group: "{{file_group_nsd_conf}}"
    validate: "{{file_validate_nsd_conf}}"
  tags:
    - nsd

- name: create file nsd.cfg
  template:
    src: "{{file_src_nsd_cfg}}"
    dest: "{{file_dst_nsd_cfg}}"
    mode: "{{file_mode_nsd_cfg}}"
    owner: "{{file_owner_nsd_cfg}}"
    group: "{{file_group_nsd_cfg}}"
  notify: reload service monit
  when: (nsd_monitor_monit_state is match('true|yes|enable'))
  tags:
    - nsd

- name: status nsd
  command: "{{command_cmd_status_nsd}}"
  register: register_status_nsd
  changed_when: (register_status_nsd.rc > 1)
  failed_when: (register_status_nsd.rc > 1)
  check_mode: 'no'
  tags:
    - nsd

- name: disable nsd
  command: "{{command_cmd_disable_nsd}}"
  check_mode: 'no'
  when: register_status_nsd.rc == 0
  tags:
    - nsd

- name: check nsd
  command: "{{command_cmd_check_nsd}}"
  register: register_check_nsd
  changed_when: (register_check_nsd.rc > 1)
  failed_when: (register_check_nsd.rc > 1)
  check_mode: 'no'
  tags:
    - nsd

- name: stop nsd
  command: "{{command_cmd_stop_nsd}}"
  check_mode: 'no'
  when: register_check_nsd.rc == 0
  tags:
    - nsd
