---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - syslogd

- name: config line syslogd_flags
  lineinfile:
    state: present
    line: "{{file_line_syslogd_flags}}=-h # Ansible: Configure syslogd"
    regexp: "^{{file_line_syslogd_flags}}=.*"
    dest: "{{file_dst_syslogd_flags}}"
    create: True
  tags:
    - syslogd

- name: create file syslog.conf
  template:
    src: "{{file_src_syslog_conf}}"
    dest: "{{file_dst_syslog_conf}}"
    mode: "{{file_mode_syslog_conf}}"
    owner: "{{file_owner_syslog_conf}}"
    group: "{{file_group_syslog_conf}}"
  tags:
    - syslogd

- name: remove file syslogd.cfg
  file:
    state: absent
    path: "{{file_dst_syslogd_cfg}}"
  notify: reload monit
  tags:
    - syslogd

- name: create file syslogd.pf
  template:
    src: "{{file_src_syslogd_pf}}"
    dest: "{{file_dst_syslogd_pf}}"
    mode: "{{file_mode_syslogd_pf}}"
    owner: "{{file_owner_syslogd_pf}}"
    group: "{{file_group_syslogd_pf}}"
  notify: reload pf
  when: (syslogd_pf_state == True)
  tags:
    - syslogd

- name: remove file syslogd.pf
  file:
    state: absent
    path: "{{file_dst_syslogd_pf}}"
  notify: reload pf
  when: (syslogd_pf_state == False)
  tags:
    - syslogd

- name: config file includes.conf
  lineinfile:
    state: "{{'present' if (syslogd_pf_state == True) else 'absent'}}"
    line: "{{file_line_includes_conf}}"
    regexp: "{{file_regexp_includes_conf}}"
    dest: "{{file_dst_includes_conf}}"
    create: True
  notify:
    - validate pf
    - reload pf
  tags:
    - syslogd

- name: status syslogd
  command: "{{command_cmd_status_syslogd}}"
  register: register_status_syslogd
  changed_when: (register_status_syslogd.rc > 1)
  failed_when: (register_status_syslogd.rc > 1)
  tags:
    - syslogd

- name: disable syslogd
  command: "{{command_cmd_disable_syslogd}}"
  check_mode: False
  when: register_status_syslogd.rc == 0
  tags:
    - syslogd

- name: check syslogd
  command: "{{command_cmd_check_syslogd}}"
  register: register_check_syslogd
  changed_when: (register_check_syslogd.rc > 1)
  failed_when: (register_check_syslogd.rc > 1)
  check_mode: False
  tags:
    - syslogd

- name: stop syslogd
  command: "{{command_cmd_stop_syslogd}}"
  check_mode: False
  when: register_check_syslogd.rc == 0
  tags:
    - syslogd
